export const ANSWER_SHORT_QUESTION_DATA = [
  { id: '1', text: "What day comes after Monday?", answer: "Tuesday", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/1.mp3'},
  { id: '2', text: "How many hours are there in a day?", answer: "24", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/2.mp3' },
  { id: '3', text: "Which month has 28 days?", answer: "February", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/3.mp3'},
  { id: '4', text: "What is the opposite of hot?", answer: "Cold", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/4.mp3'},
  { id: '5', text: "How many wheels does a bicycle have?", answer: "Two", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/5.mp3'},
  { id: '6', text: "What do we use to cut paper?", answer: "Scissors", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/6.mp3'},
  { id: '7', text: "Which colour is a banana?", answer: "Yellow", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/7.mp3'},
  { id: '8', text: "What is the capital of France?", answer: "Paris", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/8.mp3'},
  { id: '9', text: "How many fingers do you have on one hand?", answer: "Five", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/9.mp3'},
  { id: '10', text: "What do you wear on your feet?", answer: "Shoes / Socks", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/10.mp3'},
  { id: '11', text: "Which animal says meow?", answer: "Cat", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/11.mp3'},
  { id: '12', text: "What is H2O commonly known as?", answer: "Water", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/12.mp3'},
  { id: '13', text: "What do bees produce?", answer: "Honey", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/13.mp3'},
  { id: '14', text: "Which season comes after winter?", answer: "Spring", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/14.mp3'},
  { id: '15', text: "What do you use to brush your teeth?", answer: "Toothbrush", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/15.mp3'},
  { id: '16', text: "Where does a king live?", answer: "Palace / Castle", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/16.mp3'},
  { id: '17', text: "What is the opposite of left?", answer: "Right", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/17.mp3'},
  { id: '18', text: "How many legs does a spider have?", answer: "Eight", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/18.mp3'},
  { id: '19', text: "What color is the sky on a clear day?", answer: "Blue", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/19.mp3'},
  { id: '20', text: "Which instrument has black and white keys?", answer: "Piano", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/20.mp3'},
  { id: '21', text: "Who checks your teeth?", answer: "Dentist", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/21.mp3'},
  { id: '22', text: "What do you use to write on a blackboard?", answer: "Chalk", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/22.mp3'},
  { id: '23', text: "Which geometric shape has three sides?", answer: "Triangle", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/23.mp3'},
  { id: '24', text: "What is the frozen form of water?", answer: "Ice", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/24.mp3'},
  { id: '25', text: "In which direction does the sun rise?", answer: "East", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/25.mp3'},
  { id: '26', text: "What do you call a person who flies a plane?", answer: "Pilot", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/26.mp3'},
  { id: '27', text: "Which month comes before January?", answer: "December", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/27.mp3'},
  { id: '28', text: "What is the largest mammal in the world?", answer: "Blue Whale", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/28.mp3'},
  { id: '29', text: "How many cents are in a dollar?", answer: "100", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/29.mp3'},
  { id: '30', text: "What do we breathe to survive?", answer: "Oxygen / Air", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/30.mp3'},
  { id: '31', text: "Which device is used to make a call?", answer: "Telephone / Mobile", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/31.mp3'},
  { id: '32', text: "What color is grass?", answer: "Green", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/32.mp3'},
  { id: '33', text: "Who delivers the mail?", answer: "Postman", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/33.mp3'},
  { id: '34', text: "What is the opposite of fast?", answer: "Slow", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/34.mp3'},
  { id: '35', text: "Where do fish live?", answer: "Water / Ocean / River", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/35.mp3'},
  { id: '36', text: "What do you use to dry yourself after a shower?", answer: "Towel", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/36.mp3'},
  { id: '37', text: "Which planet do we live on?", answer: "Earth", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/37.mp3'},
  { id: '38', text: "How many days are in a year?", answer: "365", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/38.mp3'},
  { id: '39', text: "What is the top of a house called?", answer: "Roof", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/39.mp3'},
  { id: '40', text: "What do cars drive on?", answer: "Road / Street", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/40.mp3'},
  { id: '41', text: "Which organ pumps blood around the body?", answer: "Heart", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/41.mp3'},
  { id: '42', text: "What is the opposite of start?", answer: "Stop / End", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/42.mp3'},
  { id: '43', text: "How many sides does a square have?", answer: "Four", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/43.mp3'},
  { id: '44', text: "What do you use to smell things?", answer: "Nose", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/44.mp3'},
  { id: '45', text: "Which animal has a long neck?", answer: "Giraffe", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/45.mp3'},
  { id: '46', text: "What falls from the sky when it rains?", answer: "Water / Raindrops", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/46.mp3'},
  { id: '47', text: "What is 5 plus 5?", answer: "10", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/47.mp3'},
  { id: '48', text: "Which room do you cook in?", answer: "Kitchen", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/48.mp3'},
  { id: '49', text: "What is the opposite of up?", answer: "Down", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/49.mp3'},
  { id: '50', text: "What do you read?", answer: "Book", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/50.mp3'},
  { id: '51', text: "Who teaches students?", answer: "Teacher", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/51.mp3'},
  { id: '52', text: "What is the capital of the UK?", answer: "London", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/52.mp3'},
  { id: '53', text: "How many months are in a year?", answer: "12", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/53.mp3'},
  { id: '54', text: "What do you use to tell the time?", answer: "Clock / Watch", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/54.mp3'},
  { id: '55', text: "Which bird can swim but cannot fly?", answer: "Penguin", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/55.mp3'},
  { id: '56', text: "What comes out of a volcano?", answer: "Lava", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/56.mp3'},
  { id: '57', text: "What is the opposite of dark?", answer: "Light", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/57.mp3'},
  { id: '58', text: "Which fruit is red and has seeds on the outside?", answer: "Strawberry", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/58.mp3'},
  { id: '59', text: "What do you use to unlock a door?", answer: "Key", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/59.mp3'},
  { id: '60', text: "Where do you sleep?", answer: "Bedroom / Bed", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/60.mp3'},
  { id: '61', text: "Which animal is known as man's best friend?", answer: "Dog", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/61.mp3'},
  { id: '62', text: "What is the color of snow?", answer: "White", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/62.mp3'},
  { id: '63', text: "What do you use to protect yourself from rain?", answer: "Umbrella", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/63.mp3'},
  { id: '64', text: "Which season is the hottest?", answer: "Summer", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/64.mp3'},
  { id: '65', text: "What do you use to eat soup?", answer: "Spoon", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/65.mp3'},
  { id: '66', text: "What is the opposite of empty?", answer: "Full", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/66.mp3'},
  { id: '67', text: "How many players are in a football team?", answer: "11", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/67.mp3'},
  { id: '68', text: "Which vehicle runs on tracks?", answer: "Train", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/68.mp3'},
  { id: '69', text: "What do you wear on your hands in winter?", answer: "Gloves", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/69.mp3'},
  { id: '70', text: "Which animal gives us wool?", answer: "Sheep", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/70.mp3'},
  { id: '71', text: "What is the fluid that circulates in your veins?", answer: "Blood", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/71.mp3'},
  { id: '72', text: "What is the opposite of happy?", answer: "Sad", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/72.mp3'},
  { id: '73', text: "Which celestial body shines at night?", answer: "Moon", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/73.mp3'},
  { id: '74', text: "What do you call a baby dog?", answer: "Puppy", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/74.mp3'},
  { id: '75', text: "What is the meal eaten in the morning?", answer: "Breakfast", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/75.mp3'},
  { id: '76', text: "Which animal has a trunk?", answer: "Elephant", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/76.mp3'},
  { id: '77', text: "What is the opposite of rich?", answer: "Poor", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/77.mp3'},
  { id: '78', text: "How many days are in a week?", answer: "Seven", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/78.mp3'},
  { id: '79', text: "What do you use to see things?", answer: "Eyes", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/79.mp3'},
  { id: '80', text: "Which material comes from trees?", answer: "Wood", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/80.mp3'},
  { id: '81', text: "What is 10 minus 3?", answer: "7", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/81.mp3'},
  { id: '82', text: "Which room do you bathe in?", answer: "Bathroom", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/82.mp3'},
  { id: '83', text: "What is the opposite of hard?", answer: "Soft", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/83.mp3'},
  { id: '84', text: "What do you use to type on a computer?", answer: "Keyboard", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/84.mp3'},
  { id: '85', text: "Which insect makes a web?", answer: "Spider", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/85.mp3'},
  { id: '86', text: "What is the library filled with?", answer: "Books", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/86.mp3'},
  { id: '87', text: "Who puts out fires?", answer: "Firefighter", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/87.mp3'},
  { id: '88', text: "What is the opposite of young?", answer: "Old", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/88.mp3'},
  { id: '89', text: "Which country has a maple leaf on its flag?", answer: "Canada", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/89.mp3'},
  { id: '90', text: "What do you use to cut steak?", answer: "Knife", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/90.mp3'},
  { id: '91', text: "Which animal is the tallest?", answer: "Giraffe", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/91.mp3'},
  { id: '92', text: "What comes after the number 19?", answer: "20", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/92.mp3'},
  { id: '93', text: "Where do you buy stamps?", answer: "Post Office", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/93.mp3'},
  { id: '94', text: "What is the opposite of wet?", answer: "Dry", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/94.mp3'},
  { id: '95', text: "Which planet is known as the Red Planet?", answer: "Mars", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/95.mp3'},
  { id: '96', text: "What do you use to listen to music?", answer: "Headphones / Ears", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/96.mp3'},
  { id: '97', text: "Which animal carries its house on its back?", answer: "Snail / Turtle", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/97.mp3'},
  { id: '98', text: "What is the opposite of silence?", answer: "Noise", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/98.mp3'},
  { id: '99', text: "How many zeroes are in one thousand?", answer: "Three", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/99.mp3'},
  { id: '100', text: "What do you use to sweep the floor?", answer: "Broom", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/100.mp3'},
  { id: '101', text: "If you divide something into two equal parts, what is each part called?", answer: "Half", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/101.mp3'},
  { id: '102', text: "If a clock shows 3:00, how many hours until it shows 9:00?", answer: "Six", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/102.mp3'},
  { id: '103', text: "What do you call a shape with four equal sides?", answer: "Square", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/103.mp3'},
  { id: '104', text: "If someone cannot hear, what disability do they have?", answer: "Deafness", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/104.mp3'},
  { id: '105', text: "What color do you get when you mix red and blue?", answer: "Purple", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/105.mp3'},
  { id: '106', text: "What do you call the person who writes a book?", answer: "Author", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/106.mp3'},
  { id: '107', text: "If something happens every year, what do we call it?", answer: "Annual", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/107.mp3'},
  { id: '108', text: "What do you call a person who travels to space?", answer: "Astronaut", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/108.mp3'},
  { id: '109', text: "If you are not early and not late, what are you?", answer: "On time", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/109.mp3'},
  { id: '110', text: "What do you call the line that divides a circle into two equal halves?", answer: "Diameter", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/110.mp3'},
  { id: '111', text: "What do you pay back to a bank in addition to the money borrowed?", answer: "Interest", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/111.mp3'},
  { id: '112', text: "What do you call a person who studies the past through objects?", answer: "Archaeologist", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/112.mp3'},
  { id: '113', text: "If something is not fake, what is it?", answer: "Real", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/113.mp3'},
  { id: '114', text: "What number comes after 99?", answer: "One hundred", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/114.mp3'},
  { id: '115', text: "What book do you use to find the meaning of a word?", answer: "Dictionary", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/115.mp3'},
  { id: '116', text: "What season comes after summer?", answer: "Autumn", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/116.mp3'},
  { id: '117', text: "What do you call a triangle with one right angle?", answer: "Right triangle", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/117.mp3'},
  { id: '118', text: "What do you call the money you earn from working?", answer: "Salary", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/118.mp3'},
  { id: '119', text: "What structure helps you cross a river by foot?", answer: "Bridge", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/119.mp3'},
  { id: '120', text: "What do you call a person who fixes water pipes?", answer: "Plumber", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/120.mp3'},
  { id: '121', text: "What word describes something extremely large?", answer: "Huge", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/121.mp3'},
  { id: '122', text: "What is the study of numbers called?", answer: "Mathematics", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/122.mp3'},
  { id: '123', text: "What tool do you use to cut paper?", answer: "Scissors", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/123.mp3'},
  { id: '124', text: "What do you call a person who buys goods or services?", answer: "Customer", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/124.mp3'},
  { id: '125', text: "What device do you look at to know the time?", answer: "Clock", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/125.mp3'},
  { id: '126', text: "What is the study of how living things are classified called?", answer: "Taxonomy", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/126.mp3'},
  { id: '127', text: "What is a word that has the opposite meaning of another word?", answer: "Antonym", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/127.mp3'},
  { id: '128', text: "What do we call the outermost layer of the Earth?", answer: "Crust", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/128.mp3'},
  { id: '129', text: "What is the economic term for a decrease in general price levels?", answer: "Deflation", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/129.mp3'},
  { id: '130', text: "What do we call animals that are active at night?", answer: "Nocturnal", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/130.mp3'},
  { id: '131', text: "What is a government ruled by a king or queen called?", answer: "Monarchy", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/131.mp3'},
  { id: '132', text: "What is the process of water turning into vapor called?", answer: "Evaporation", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/132.mp3'},
  { id: '133', text: "What is the scientific study of the human mind and behavior?", answer: "Psychology", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/133.mp3'},
  { id: '134', text: "What is the imaginary line running from the North Pole to the South Pole?", answer: "Prime Meridian", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/134.mp3'},
  { id: '135', text: "What do we call a substance that speeds up a chemical reaction?", answer: "Catalyst", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/135.mp3'},
  { id: '136', text: "What is the ability of a material to return to its original shape after being stretched?", answer: "Elasticity", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/136.mp3'},
  { id: '137', text: "What is a word that sounds the same but has a different meaning?", answer: "Homonym", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/137.mp3'},
  { id: '138', text: "What is the scientific study of the origin and development of the universe?", answer: "Cosmology", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/138.mp3'},
  { id: '139', text: "What do we call a disease that spreads across many countries or continents?", answer: "Pandemic", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/139.mp3'},
  { id: '140', text: "What is the smallest unit of life?", answer: "Cell", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/140.mp3'},
  { id: '141', text: "What is a conclusion drawn from evidence and reasoning called?", answer: "Inference", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/141.mp3'},
  { id: '142', text: "What do we call the energy stored in an object due to its position?", answer: "Potential energy", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/142.mp3'},
  { id: '143', text: "What is a government in which citizens vote directly on laws?", answer: "Direct democracy", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/143.mp3'},
  { id: '144', text: "What is the process by which plants release water vapor into the air?", answer: "Transpiration", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/144.mp3'},
  { id: '145', text: "What do we call a statement that contradicts itself but may still be true?", answer: "Paradox", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/145.mp3'},
  { id: '146', text: "What is the study of the structure of the human body?", answer: "Anatomy", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/146.mp3'},
  { id: '147', text: "What do we call a group of stars forming a recognizable pattern?", answer: "Constellation", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/147.mp3'},
  { id: '148', text: "What is the ability to understand and share the feelings of others?", answer: "Empathy", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/148.mp3'},
  { id: '149', text: "What do we call a chemical that donates protons in a reaction?", answer: "Acid", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/149.mp3'},
  { id: '150', text: "What is the point where two lines meet called?", answer: "Vertex", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/answer_short_question/150.mp3'},
];