export const REPEAT_SENTENCE_QUESTIONS = [
  { id: '1', text: "The lecture will begin in a few minutes.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/1.mp3' },
  { id: '2', text: "Please submit your assignment by Friday.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/2.mp3'},
  { id: '3', text: "The library closes early on weekends.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/3.mp3'},
  { id: '4', text: "Attendance is required for all tutorials.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/4.mp3'},
  { id: '5', text: "The results will be announced tomorrow.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/5.mp3'},
  { id: '6', text: "Coffee is available in the student lounge.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/6.mp3'},
  { id: '7', text: "The timetable has been updated online.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/7.mp3'},
  { id: '8', text: "Your password needs to be changed regularly.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/8.mp3'},
  { id: '9', text: "The seminar will cover several key topics.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/9.mp3'},
  { id: '10', text: "Tutors are available for extra support.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/10.mp3'},
  { id: '11', text: "Students must register for classes before the deadline.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/11.mp3'},
  { id: '12', text: "The research project requires both data collection and analysis.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/12.mp3'},
  { id: '13', text: "Please remember to turn off your microphone after speaking.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/13.mp3'},
  { id: '14', text: "The university cafeteria offers a variety of healthy meals.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/14.mp3'},
  { id: '15', text: "All participants are expected to attend the final workshop.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/15.mp3'},
  { id: '16', text: "The professor explained the concept using several examples.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/16.mp3'},
  { id: '17', text: "You can book an appointment through the online portal.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/17.mp3'},
  { id: '18', text: "The new policy will take effect at the start of next month.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/18.mp3'},
  { id: '19', text: "Group discussions help students develop critical thinking skills.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/19.mp3'},
  { id: '20', text: "The library provides access to thousands of digital resources.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/20.mp3'},
  { id: '21', text: "The results of the experiment were significantly different from what researchers predicted.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/21.mp3'},
  { id: '22', text: "Students are encouraged to review the course materials before attending each lecture.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/22.mp3'},
  { id: '23', text: "The conference will bring together experts from a wide range of academic disciplines.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/23.mp3'},
  { id: '24', text: "Please ensure that all electronic devices are switched off during the presentation.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/24.mp3'},
  { id: '25', text: "The study found a strong correlation between sleep quality and academic performance.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/25.mp3'},
  { id: '26', text: "Several factors must be considered when evaluating the effectiveness of the program.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/25.mp3'},
  { id: '27', text: "The university is planning to expand its research facilities over the next few years.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/27.mp3'},
  { id: '28', text: "The professor emphasized the importance of referencing all sources accurately.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/28.mp3'},
  { id: '29', text: "Many students find it helpful to form study groups before major examinations.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/29.mp3'},
  { id: '30', text: "The new software update includes several features designed to improve user experience.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/30.mp3'},
  { id: '31', text: "The committee will review all applications carefully before making a final decision.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/31.mp3'},
  { id: '32', text: "Researchers have identified several variables that may influence the outcome of the study.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/32.mp3'},
  { id: '33', text: "The lecture provided a detailed overview of recent developments in environmental science.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/33.mp3'},
  { id: '34', text: "Students are reminded to check their university email accounts for important announcements.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/34.mp3'},
  { id: '35', text: "The course requires a solid understanding of basic mathematical principles and formulas.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/35.mp3'},
  { id: '36', text: "The department is offering additional workshops to help students prepare for the exam.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/36.mp3'},
  { id: '37', text: "The findings suggest that early intervention can significantly improve long‑term results.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/37.mp3'},
  { id: '38', text: "The speaker highlighted the need for greater collaboration between industry and academia.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/38.mp3'},
  { id: '39', text: "The survey revealed that most participants preferred online learning over traditional classes.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/39.mp3'},
  { id: '40', text: "The assignment must be submitted electronically through the learning management system.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/40.mp3'},
  { id: '41', text: "The research team conducted a series of experiments to test the reliability of the new method.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/41.mp3'},
  { id: '42', text: "Students who require special accommodations should contact the support office as soon as possible.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/42.mp3'},
  { id: '43', text: "The presentation explored how technological innovation is reshaping global communication patterns.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/43.mp3'},
  { id: '44', text: "The professor encouraged students to think critically about the ethical implications of their work.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/44.mp3'},
  { id: '45', text: "The study demonstrated that consistent practice leads to measurable improvements in performance.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/45.mp3'},
  { id: '46', text: "The university is committed to creating an inclusive environment for all members of the community.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/46.mp3'},
  { id: '47', text: "The workshop will introduce practical strategies for managing time more effectively.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/47.mp3'},
  { id: '48', text: "The results indicate that environmental factors play a significant role in human behaviour.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/48.mp3'},
  { id: '49', text: "The speaker discussed several challenges facing the healthcare system in the coming decade.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/49.mp3'},
  { id: '50', text: "The course aims to develop students’ ability to analyze complex information with confidence.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/50.mp3'},
  { id: '51', text: "The library will close early during the holiday period.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/51.mp3'},
  { id: '52', text: "Please submit your assignment before the end of the week.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/52.mp3'},
  { id: '53', text: "The lecture tomorrow will start ten minutes later than usual.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/53.mp3'},
  { id: '54', text: "Students must wear their ID cards at all times on campus.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/54.mp3'},
  { id: '55', text: "The cafeteria offers vegetarian meals every day.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/55.mp3'},
  { id: '56', text: "Your timetable will be available online next Monday.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/56.mp3'},
  { id: '57', text: "The teacher will explain the new topic after the break.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/57.mp3'},
  { id: '58', text: "Please check your email for important course updates.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/58.mp3'},
  { id: '59', text: "The meeting has been moved to a larger room.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/59.mp3'},
  { id: '60', text: "You can borrow up to five books from the library.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/60.mp3'},
  { id: '61', text: "The bus to the city leaves every thirty minutes.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/61.mp3'},
  { id: '62', text: "Make sure you save your work before closing the computer.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/62.mp3'},
  { id: '63', text: "The science lab requires safety goggles for all experiments.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/63.mp3'},
  { id: '64', text: "Please speak clearly so everyone can understand you.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/64.mp3'},
  { id: '65', text: "The museum offers free entry on the first Sunday of each month.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/65.mp3'},
  { id: '66', text: "Your student card can also be used to pay for printing.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/66.mp3'},
  { id: '67', text: "The weather is expected to be warm and sunny this weekend.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/67.mp3'},
  { id: '68', text: "The library has extended its opening hours for exam season.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/68.mp3'},
  { id: '69', text: "Please turn off your mobile phone during the presentation.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/69.mp3'},
  { id: '70', text: "The teacher will give feedback on your project next week.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/70.mp3'},
  { id: '71', text: "You must register for the workshop before Friday.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/71.mp3'},
  { id: '72', text: "The classroom has been rearranged to allow more space.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/72.mp3'},
  { id: '73', text: "Please keep your desk clean and tidy at all times.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/73.mp3'},
  { id: '74', text: "The school will host a cultural festival next month.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/74.mp3'},
  { id: '75', text: "The computer system will be updated overnight.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/75.mp3'},
  { id: '76', text: "Please follow the signs to the main entrance.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/76.mp3'},
  { id: '77', text: "The teacher will check attendance at the beginning of class.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/77.mp3'},
  { id: '78', text: "The library is a quiet area for study and reading.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/78.mp3'},
  { id: '79', text: "You can ask the receptionist for help if you need it.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/79.mp3'},
  { id: '80', text: "The bus service may be delayed due to heavy traffic.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/80.mp3'},
  { id: '81', text: "Please return the equipment after you finish using it.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/81.mp3'},
  { id: '82', text: "The school store sells notebooks, pens, and other supplies.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/82.mp3'},
  { id: '83', text: "The next class will focus on improving speaking skills.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/83.mp3'},
  { id: '84', text: "Please wait in line until it is your turn.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/84.mp3'},
  { id: '85', text: "The teacher will explain the homework at the end of class.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/85.mp3'},
  { id: '86', text: "The library staff can help you find the books you need.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/86.mp3'},
  { id: '87', text: "The building will be closed for maintenance this weekend.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/87.mp3'},
  { id: '88', text: "Please check the notice board for important announcements.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/88.mp3'},
  { id: '89', text: "The school encourages students to join after‑school clubs.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/89.mp3'},
  { id: '90', text: "The exam results will be released next Wednesday.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/90.mp3'},
  { id: '91', text: "Please keep your voice down while others are studying.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/91.mp3'},
  { id: '92', text: "The teacher will hand out the worksheets shortly.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/92.mp3'},
  { id: '93', text: "The bus stop is located just outside the main gate.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/93.mp3'},
  { id: '94', text: "Please bring your textbook to every class.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/94.mp3'},
  { id: '95', text: "The school will organize a field trip in early June.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/95.mp3'},
  { id: '96', text: "The computer lab is open until eight in the evening.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/96.mp3'},
  { id: '97', text: "Please make sure your phone is on silent mode.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/97.mp3'},
  { id: '98', text: "The teacher will review the answers with the class.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/98.mp3'},
  { id: '99', text: "The library offers free Wi‑Fi for all students.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/99.mp3'},
  { id: '100', text: "Please hand in your homework at the front desk.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/100.mp3'},
  { id: '101', text: "The class will begin as soon as everyone is seated.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/101.mp3'},
  { id: '102', text: "The school cafeteria closes at three in the afternoon.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/102.mp3'},
  { id: '103', text: "Please check the schedule for any room changes.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/103.mp3'},
  { id: '104', text: "The teacher will give a short quiz at the end of the lesson.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/104.mp3'},
  { id: '105', text: "The building has elevators on both sides of the hall.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/105.mp3'},
  { id: '106', text: "Please keep your belongings with you at all times.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/106.mp3'},
  { id: '107', text: "The library has a quiet study area on the second floor.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/107.mp3'},
  { id: '108', text: "The school will provide materials for the workshop.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/108.mp3'},
  { id: '109', text: "Please raise your hand if you have a question.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/109.mp3'},
  { id: '110', text: "The teacher will explain the project guidelines today.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/110.mp3'},
  { id: '111', text: "The bus arrives at the station every fifteen minutes.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/111.mp3'},
  { id: '112', text: "Please check your timetable before coming to class.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/112.mp3'},
  { id: '113', text: "The school encourages students to read every day.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/113.mp3'},
  { id: '114', text: "The teacher will show a short video during the lesson.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/114.mp3'},
  { id: '115', text: "Please keep the classroom clean and organized.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/115.mp3'},
  { id: '116', text: "The library offers free workshops on research skills.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/116.mp3'},
  { id: '117', text: "The next lesson will focus on listening practice.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/117.mp3'},
  { id: '118', text: "Please arrive five minutes early for your appointment.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/118.mp3'},
  { id: '119', text: "The school will host a guest speaker next week.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/119.mp3'},
  { id: '120', text: "Please check your work carefully before submitting it.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/120.mp3'},
  { id: '121', text: "The teacher will collect the forms at the end of class.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/121.mp3'},
  { id: '122', text: "The cafeteria is offering new menu options this month.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/122.mp3'},
  { id: '123', text: "Please turn off the lights when you leave the room.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/123.mp3'},
  { id: '124', text: "The school will send an email with further instructions.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/124.mp3'},
  { id: '125', text: "The library has computers available for student use.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/125.mp3'},
  { id: '126', text: "Please wait outside until the teacher arrives.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/126.mp3'},
  { id: '127', text: "The class will continue after a short break.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/127.mp3'},
  { id: '128', text: "The school encourages students to participate in sports.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/128.mp3'},
  { id: '129', text: "Please check the weather before planning outdoor activities.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/129.mp3'},
  { id: '130', text: "The teacher will explain the grammar rules again.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/130.mp3'},
  { id: '131', text: "The library will host a reading event next Friday.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/131.mp3'},
  { id: '132', text: "Please bring a notebook to take notes during the lecture.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/132.mp3'},
  { id: '133', text: "The school will provide transportation for the trip.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/133.mp3'},
  { id: '134', text: "Please keep your phone away during the lesson.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/134.mp3'},
  { id: '135', text: "The teacher will answer questions at the end of the class.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/135.mp3'},
  { id: '136', text: "The library is offering free printing this week.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/136.mp3'},
  { id: '137', text: "Please follow the instructions carefully.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/137.mp3'},
  { id: '138', text: "The next class will focus on reading comprehension.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/138.mp3'},
  { id: '139', text: "Please check the lost and found for missing items.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/139.mp3'},
  { id: '140', text: "The teacher will give a short introduction to the topic.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/140.mp3'},
  { id: '141', text: "The school will organize a charity event next month.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/141.mp3'},
  { id: '142', text: "Please make sure your laptop is fully charged.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/142.mp3'},
  { id: '143', text: "The library has a new collection of English books.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/143.mp3'},
  { id: '144', text: "Please listen carefully to the instructions.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/144.mp3'},
  { id: '145', text: "The teacher will review the homework in class.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/145.mp3'},
  { id: '146', text: "The school encourages students to join study groups.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/146.mp3'},
  { id: '147', text: "Please check your email for the meeting link.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/147.mp3'},
  { id: '148', text: "The next lesson will include a short discussion.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/148.mp3'},
  { id: '149', text: "Please keep your bag under your desk during class.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/149.mp3'},
  { id: '150', text: "The teacher will explain the exam format tomorrow.", audioUrl: 'https://storage.googleapis.com/pte_flow_audio/speaking/repeat_sentence/150.mp3'},
];