export const WRITE_DICTATION_QUESTIONS = [
  //A1 LEVEL (1-10)
  { id: '1', level: 'A1', text: "The sun is very hot today.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/1.mp3" },
  { id: '2', level: 'A1', text: "She walks to school every morning.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/2.mp3" },
  { id: '3', level: 'A1', text: "Please close the door behind you.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/3.mp3" },
  { id: '4', level: 'A1', text: "I have a red car.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/4.mp3" },
  { id: '5', level: 'A1', text: "They are playing in the park.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/5.mp3" },
  { id: '6', level: 'A1', text: "My father is a doctor.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/6.mp3" },
  { id: '7', level: 'A1', text: "We eat dinner at seven o'clock.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/7.mp3" },
  { id: '8', level: 'A1', text: "The cat is sleeping on the bed.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/8.mp3" },
  { id: '9', level: 'A1', text: "He likes to read books.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/9.mp3" },
  { id: '10', level: 'A1', text: "This apple is very sweet.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/10.mp3" },

  //A2 LEVEL (11-20)
  { id: '11', level: 'A2', text: "The library will close in ten minutes.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/11.mp3"},
  { id: '12', level: 'A2', text: "Students must finish their homework on time.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/12.mp3"},
  { id: '13', level: 'A2', text: "We are planning a trip to the mountains.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/13.mp3" },
  { id: '14', level: 'A2', text: "Please turn off your phone during the movie.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/14.mp3" },
  { id: '15', level: 'A2', text: "The train leaves the station at noon.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/15.mp3" },
  { id: '16', level: 'A2', text: "She bought a new dress for the party.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/16.mp3" },
  { id: '17', level: 'A2', text: "It is important to drink plenty of water.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/17.mp3" },
  { id: '18', level: 'A2', text: "There are many interesting places to visit here.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/18.mp3" },
  { id: '19', level: 'A2', text: "He forgot to bring his keys yesterday.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/19.mp3" },
  { id: '20', level: 'A2', text: "The weather will be cloudy tomorrow.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/20.mp3" },

  //B1 LEVEL (21-71)
  { id: '21', level: 'B1', text: "The university offers a wide range of courses.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/21.mp3" },
  { id: '22', level: 'B1', text: "You need to register before the deadline passes.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/22.mp3" },
  { id: '23', level: 'B1', text: "Scientific research requires careful analysis of data.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/23.mp3" },
  { id: '24', level: 'B1', text: "All passengers must show their tickets at the gate.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/24.mp3" },
  { id: '25', level: 'B1', text: "The professor will be available for consultation on Tuesday.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/25.mp3" },
  { id: '26', level: 'B1', text: "Economic growth has slowed down in recent years.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/26.mp3" },
  { id: '27', level: 'B1', text: "This assignment counts towards your final grade.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/27.mp3" },
  { id: '28', level: 'B1', text: "Modern technology has changed the way we communicate.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/28.mp3" },
  { id: '29', level: 'B1', text: "Please ensure that your essay is referenced correctly.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/29.mp3" },
  { id: '30', level: 'B1', text: "The new policy aims to reduce plastic waste.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/30.mp3" },
  { id: '31', level: 'B1', text: "The library will close early on Friday.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/31.mp3" },
  { id: '32', level: 'B1', text: "Students must submit the form by next week.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/32.mp3" },
  { id: '33', level: 'B1', text: "The lecture starts at nine in the morning.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/33.mp3" },
  { id: '34', level: 'B1', text: "Please check your email for the latest update.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/34.mp3" },
  { id: '35', level: 'B1', text: "The meeting was moved to a larger room.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/35.mp3" },
  { id: '36', level: 'B1', text: "Our class will visit the science museum tomorrow.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/36.mp3" },
  { id: '37', level: 'B1', text: "The new timetable will be shared soon.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/37.mp3" },
  { id: '38', level: 'B1', text: "Please bring your student card to the exam.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/38.mp3" },
  { id: '39', level: 'B1', text: "The cafeteria offers healthy meals every day.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/39.mp3" },
  { id: '40', level: 'B1', text: "Group assignments are due at the end of the month.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/40.mp3" },
  { id: '41', level: 'B1', text: "The library computers are available for all students.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/41.mp3" },
  { id: '42', level: 'B1', text: "Please save your work before closing the program.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/42.mp3" },
  { id: '43', level: 'B1', text: "The bus arrives every fifteen minutes.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/43.mp3" },
  { id: '44', level: 'B1', text: "Our teacher will explain the project tomorrow.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/44.mp3" },
  { id: '45', level: 'B1', text: "You must go to the toilet before the exam starts.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/45.mp3" },
  { id: '46', level: 'B1', text: "Please keep your phone silent during the lecture.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/46.mp3" },
  { id: '47', level: 'B1', text: "The results will be published on the website.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/47.mp3" },
  { id: '48', level: 'B1', text: "The workshop begins at ten o’clock sharp.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/48.mp3" },
  { id: '49', level: 'B1', text: "Students can book study rooms online.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/49.mp3" },
  { id: '50', level: 'B1', text: "The library has extended hours during exams.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/50.mp3" },
  { id: '51', level: 'B1', text: "Please return the books by the due date.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/51.mp3" },
  { id: '52', level: 'B1', text: "The weather forecast predicts heavy rain tomorrow.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/52.mp3" },
  { id: '53', level: 'B1', text: "Our class will have a short quiz next week.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/53.mp3" },
  { id: '54', level: 'B1', text: "The teacher will post the notes after the lesson.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/54.mp3" },
  { id: '55', level: 'B1', text: "Please follow the signs to the main entrance.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/55.mp3" },
  { id: '56', level: 'B1', text: "The computer lab opens at eight every morning.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/56.mp3" },
  { id: '57', level: 'B1', text: "Students should check the schedule before registering.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/57.mp3" },
  { id: '58', level: 'B1', text: "The library offers free printing for all members.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/58.mp3" },
  { id: '59', level: 'B1', text: "Please hand in your assignment at the front desk.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/59.mp3" },
  { id: '60', level: 'B1', text: "The next class will focus on reading skills.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/60.mp3" },
  { id: '61', level: 'B1', text: "The campus tour starts at the main gate.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/61.mp3" },
  { id: '62', level: 'B1', text: "Please arrive early to find a good seat.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/62.mp3" },
  { id: '63', level: 'B1', text: "The teacher will review the answers in class.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/63.mp3" },
  { id: '64', level: 'B1', text: "Our group needs to finish the presentation soon.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/64.mp3" },
  { id: '65', level: 'B1', text: "The library staff can help you find resources.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/65.mp3" },
  { id: '66', level: 'B1', text: "Please check the notice board for new announcements.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/66.mp3" },
  { id: '67', level: 'B1', text: "The exam will cover all chapters from the book.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/67.mp3" },
  { id: '68', level: 'B1', text: "Students must wear their ID badges on campus.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/68.mp3" },
  { id: '69', level: 'B1', text: "The cafeteria will introduce new menu items.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/69.mp3" },
  { id: '70', level: 'B1', text: "Please keep the classroom clean and tidy.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/70.mp3" },


  // --- B2 LEVEL (72-122)
  { id: '71', level: 'B2', text: "The results of the experiment were published in a scientific journal.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/71.mp3" },
  { id: '72', level: 'B2', text: "A thorough bibliography is a requirement for all academic assignments.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/72.mp3" },
  { id: '73', level: 'B2', text: "The campus administration is located behind the main building.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/73.mp3" },
  { id: '74', level: 'B2', text: "Certain biological functions are yet to be fully understood.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/74.mp3" },
  { id: '75', level: 'B2', text: "The lecture on history has been rescheduled to Friday.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/75.mp3" },
  { id: '76', level: 'B2', text: "Students are encouraged to think critical about the subject matter.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/76.mp3" },
  { id: '77', level: 'B2', text: "The department is currently reviewing its admission procedures.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/77.mp3" },
  { id: '78', level: 'B2', text: "Globalisation often leads to the homogenization of cultural values.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/78.mp3" },
  { id: '79', level: 'B2', text: "Financial difficulties can cause stress and anxiety for students.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/79.mp3"},
  { id: '80', level: 'B2', text: "Collaboration between departments is essential for this project.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/80.mp3" },
  { id: '81', level: 'B2', text: "The university will introduce several new courses next semester.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/81.mp3" },
  { id: '82', level: 'B2', text: "Please review the updated guidelines before submitting your work.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/82.mp3" },
  { id: '83', level: 'B2', text: "The research project requires careful planning and collaboration.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/83.mp3" },
  { id: '84', level: 'B2', text: "Students must register early to secure their preferred timetable.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/84.mp3" },
  { id: '85', level: 'B2', text: "The lecture will examine recent developments in global trade.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/85.mp3" },
  { id: '86', level: 'B2', text: "All participants are expected to attend the final workshop.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/86.mp3" },
  { id: '87', level: 'B2', text: "The committee will review the proposal later this week.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/87.mp3" },
  { id: '88', level: 'B2', text: "Please upload your presentation slides before the deadline.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/88.mp3" },
  { id: '89', level: 'B2', text: "The new policy aims to improve workplace communication.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/89.mp3" },
  { id: '90', level: 'B2', text: "Students are encouraged to join the academic writing seminar.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/90.mp3" },
  { id: '91', level: 'B2', text: "The library has expanded its digital collection this year.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/91.mp3" },
  { id: '92', level: 'B2', text: "Please ensure all documents are saved in the correct format.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/92.mp3" },
  { id: '93', level: 'B2', text: "The conference will focus on emerging environmental issues.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/93.mp3" },
  { id: '94', level: 'B2', text: "Group leaders must submit a progress report every Friday.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/94.mp3" },
  { id: '95', level: 'B2', text: "The department will announce the scholarship results soon.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/95.mp3" },
  { id: '96', level: 'B2', text: "Students should check the portal for important notifications.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/96.mp3" },
  { id: '97', level: 'B2', text: "The training session will cover advanced research techniques.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/97.mp3" },
  { id: '98', level: 'B2', text: "Please contact the support team if you experience technical issues.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/98.mp3" },
  { id: '99', level: 'B2', text: "The new timetable includes additional tutorials for first‑year students.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/99.mp3" },
  { id: '100', level: 'B2', text: "The professor will discuss the assignment criteria in class.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/100.mp3" },
  { id: '101', level: 'B2', text: "Students must complete the online survey by the end of the week.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/101.mp3" },
  { id: '102', level: 'B2', text: "The research findings highlight several important trends.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/102.mp3" },
  { id: '103', level: 'B2', text: "Please follow the instructions carefully when submitting your file.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/103.mp3" },
  { id: '104', level: 'B2', text: "The workshop will explore strategies for effective teamwork.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/104.mp3" },
  { id: '105', level: 'B2', text: "The university plans to upgrade its computer facilities soon.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/105.mp3" },
  { id: '106', level: 'B2', text: "Students are required to attend all scheduled laboratory sessions.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/106.mp3" },
  { id: '107', level: 'B2', text: "The report must include clear evidence to support your argument.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/107.mp3" },
  { id: '108', level: 'B2', text: "Please check the course website for additional reading materials.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/108.mp3" },
  { id: '109', level: 'B2', text: "The seminar will address common challenges in academic writing.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/109.mp3" },
  { id: '110', level: 'B2', text: "Students should prepare questions before the discussion begins.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/110.mp3" },
  { id: '111', level: 'B2', text: "The department encourages students to participate in research projects.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/111.mp3" },
  { id: '112', level: 'B2', text: "Please submit your application before the closing date.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/112.mp3" },
  { id: '113', level: 'B2', text: "The lecture will analyse the impact of digital media on society.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/113.mp3" },
  { id: '114', level: 'B2', text: "Students must follow safety procedures during laboratory work.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/114.mp3" },
  { id: '115', level: 'B2', text: "The university will host an international conference next year.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/115.mp3" },
  { id: '116', level: 'B2', text: "Please review the feedback to improve your next assignment.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/116.mp3" },
  { id: '117', level: 'B2', text: "The research team is collecting data from multiple sources.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/117.mp3" },
  { id: '118', level: 'B2', text: "Students are advised to attend the optional revision session.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/118.mp3" },
  { id: '119', level: 'B2', text: "The presentation should include both visuals and explanations.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/119.mp3" },
  { id: '120', level: 'B2', text: "Please check the timetable for any recent changes.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/120.mp3" },

  // --- C1 LEVEL (121-135)
  { id: '121', level: 'C1', text: "The intricacies of the judicial system can be difficult to comprehend.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/121.mp3" },
  { id: '122', level: 'C1', text: "Statistical evidence suggests a correlation between the two variables.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/122.mp3" },
  { id: '123', level: 'C1', text: "The dichotomy between theory and practice is a recurring theme.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/123.mp3" },
  { id: '124', level: 'C1', text: "Subsequent analysis revealed significant discrepancies in the initial data.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/124.mp3" },
  { id: '125', level: 'C1', text: "The sustainability of this business model is currently under scrutiny.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/125.mp3" },
  { id: '126', level: 'C1', text: "The research committee will evaluate all proposals before approval.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/126.mp3" },
  { id: '127', level: 'C1', text: "Attendance at the seminar is essential for understanding the final assessment.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/127.mp3" },
  { id: '128', level: 'C1', text: "The professor emphasised the importance of critical analysis in academic writing.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/128.mp3" },
  { id: '129', level: 'C1', text: "Students are expected to reference credible sources in their reports.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/129.mp3" },
  { id: '130', level: 'C1', text: "The conference highlighted several emerging trends in global education.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/130.mp3" },
  { id: '131', level: 'C1', text: "Please ensure your presentation aligns with the required academic standards.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/131.mp3" },
  { id: '132', level: 'C1', text: "The department encourages students to participate in interdisciplinary projects.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/132.mp3" },
  { id: '133', level: 'C1', text: "The lecture examined how technology influences modern communication.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/133.mp3" },
  { id: '134', level: 'C1', text: "All participants must submit a reflective summary after the workshop.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/134.mp3" },
  { id: '135', level: 'C1', text: "The study revealed significant differences between the two research groups.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/135.mp3" },

  // --- C2 LEVEL (Proficiency) ---
  { id: '136', level: 'C2', text: "Had the preliminary findings been corroborated, the hypothesis would have stood.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/136.mp3" },
  { id: '137', level: 'C2', text: "The proliferation of digital misinformation poses an existential threat to democracy.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/137.mp3" },
  { id: '138', level: 'C2', text: "Philosophical discourse necessitates a rigorous examination of fundamental epistemological premises.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/138.mp3" },
  { id: '139', level: 'C2', text: "The juxtaposition of these conflicting ideologies creates a volatile political landscape.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/139.mp3" },
  { id: '140', level: 'C2', text: "An unequivocal commitment to ethical standards is paramount in medical research.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/140.mp3" },
  { id: '141', level: 'C2', text: "The committee reached a consensus after evaluating several complex proposals.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/141.mp3" },
  { id: '142', level: 'C2', text: "The study challenges long‑held assumptions about cultural adaptation and identity.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/142.mp3" },
  { id: '143', level: 'C2', text: "Researchers emphasised the need for transparent methods in future investigations.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/143.mp3" },
  { id: '144', level: 'C2', text: "The lecture examined how global systems influence economic resilience.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/144.mp3" },
  { id: '145', level: 'C2', text: "The findings highlight significant disparities across multiple demographic groups.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/145.mp3" },
  { id: '146', level: 'C2', text: "The report proposes a framework for addressing emerging ethical concerns.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/146.mp3" },
  { id: '147', level: 'C2', text: "The conference explored innovative strategies for sustainable development.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/147.mp3" },
  { id: '148', level: 'C2', text: "The analysis revealed subtle patterns that were previously overlooked.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/148.mp3" },
  { id: '149', level: 'C2', text: "The researcher presented a compelling argument supported by extensive evidence.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/149.mp3" },
  { id: '150', level: 'C2', text: "The project requires interdisciplinary collaboration to achieve meaningful results.", audioUrl: "https://storage.googleapis.com/pte_flow_audio/listening/%20write_from_dictation/150.mp3" }
];